import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import AnimatedPage from '../components/AnimatedPage';

export default function Home() {
  return (
    <AnimatedPage>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href='https://nextjs.org'>Next.js!</a>
          </h1>
          <Link href='/contact'>
            <a className={styles.button}>Contacts</a>
          </Link>
          <Link href='/legal'>
            <a className={styles.button}>Legal</a>
          </Link>
        </main>
      </div>
    </AnimatedPage>
  );
}
