import { useContext, useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';

import AnimatedPage from '../src/components/AnimatedPage';
import { Context as AuthContext } from '../src/globalState/context/AuthContext';
import { Context as AppContext } from '../src/globalState/context/AppContext';
import StateCheck from '../src/components/StateCheck';
import { Button } from '@material-ui/core';

export default function Home() {
  const {
    state: { token },
    fetchUserToken,
  } = useContext(AuthContext);

  const {
    state: { darkMode },
  } = useContext(AppContext);

  useEffect(() => {
    fetchUserToken();
  }, []);

  return (
    <AnimatedPage>
      <div
        style={{
          minHeight: '100vh',
          padding: '0 0.5rem',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
          height: '100vh',
        }}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main
          style={{
            padding: '5rem 0',
            flex: 1,
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
          }}>
          <h1>
            Welcome to{' '}
            <a
              style={{ color: '#0070f3', textDecoration: 'none' }}
              href='https://nextjs.org'>
              Next.js!
            </a>
          </h1>

          <div style={{ width: '15 rem' }}>
            <StateCheck state={token} label={'Token: ' + token} />
            <StateCheck state={darkMode} label='Dark Mode' />
          </div>

          <div
            style={{
              display: 'flex',
              justifyContent: 'space-between',
              width: '12rem',
            }}>
            <Link href='/login' passHref>
              <Button variant='contained' name='login'>
                Login
              </Button>
            </Link>
            <Link href='/register' passHref>
              <Button variant='contained' name='register'>
                Register
              </Button>
            </Link>
          </div>
        </main>
      </div>
    </AnimatedPage>
  );
}
